class Metrics:

    def __init__(self):
        self.best_reward = -float('inf')

    def real_episode_duration(self):...

    def virtual_episode_duration(self):...

    def episode_reward(self):...

    def episode_loss(self):...

    def episode_best_reward(self):...